In [2]:
import numpy as np

a = np.array([1, 2, 3]) # a vector has no direction
A = np.array([[1, 2, 3]]) # a 1 x 3 array that can be transposed
a_T = a[:, np.newaxis] # a' although a has no direction (3 變成3,加在後面的意思)
A_T = A.T # A'
B = A.reshape(-1, 1) # 行列轉換
C = np.array([1, 2, 3], ndmin = 2) # convert a to A
print(np.size(a))  # == print(a.size) number of elements in a
print(np.shape(A_T))  # == print(A_T.shape) , array dimension
 
D = np.array([[1, 2, 3],[4, 5, 6]])
print(D[1]) # D[1] = D[1,:] # second row and all columns
print(D[:, 1]) #逗號前面先往下看，逗號後面往右邊看
print(D[:, 0:-1])
print(D[:, 1:])
print(D[:, -2:])


3
(3, 1)
[4 5 6]
[2 5]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


In [3]:
# vector concatenation
va = np.array([1, 2, 3])
vb = np.array([4, 5, 6])
vc = np.concatenate((va, vb), axis = 0) #左右連起來# flatten a, b; try axis=1
vd = np.append(va, vb)
ve = np.hstack((va, vb)) 
vF = np.vstack((va, vb))#上下堆起來
vFF=vF.flatten()#全部弄成一列
vg = np.r_[va, vb]
vG = np.c_[va, vb]
vH = (va, vb) # a tuple
print(vF)

[[1 2 3]
 [4 5 6]]


In [2]:
#matrix concatenation
 
ma = np.array([[1, 2, 3]]) # 1 x 3
mb = np.array([[4, 5, 6]]) # 1 x 3
mc = np.hstack((ma, mb))   # 1 x 6
  
# Vertically, concatenate row-wisely 
mC = np.concatenate((ma, mb), axis = 0) # 2 x 3 #axis=0 往下排
mD = np.r_[ma, mb] # 2 x 3
mE = np.vstack((ma,mb)) #2 x 3
  
# Horizontally, concatenate column-wisely
mF = np.concatenate((ma.T, mb.T), axis =1) # 3 x 2 #axis=1往右排
mG = np.hstack((ma.T, mb.T)) # 3 x 2
mH = np.c_[ma.T, mb.T] # 3 x 2

In [4]:
S = np.array([[1, 3, 2], [6, 5, 4]])
print(S)
print(S.max())
print(S.max(0)) # column max
print(np.max(S, axis = 1)) # row max
 
a = S.flatten() # turn into vector
b = S.flatten('F') # turn into vector column-wise #第一個排完 往下抓，再去第二行
S[S < 3] = 0 # check what S looks like
 
c = [1, 2, 3, 4]
C = np.tile(c,(5,1)) # 5 x 4 matrix
d = np.reshape(C, (-1, 1)) # convert to Column vector


[[1 3 2]
 [6 5 4]]
6
[6 5 4]
[3 6]


In [5]:
import numpy as np

a = np.array([[1, 2, 3]])
a_T=a.T
print(a_T)

[[1]
 [2]
 [3]]
